### ISSUE TITLE
运行官网图像分类模型知识蒸馏教程报错

### ISSUE THREAD

**Issue by musketeera** [PaddlePaddle/PaddleSlim#570] opened 2020-12-24 07:12 UTC
我安装的是paddlepaddle2.0版本，我将下面网站教程中的代码输入进去https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/distillation_tutorial.md
然后报错AssertionError: In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and 'data()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode.
请问这种怎么解决？
![报错](https://user-images.githubusercontent.com/55349793/103069430-554a3800-45fa-11eb-89e4-56b9b2fe3f6a.PNG)

**Comment by baiyfbupt** [comment] 2020-12-29 08:43
您好，报错来源于Paddle2.0版本默认使用动态图，
可以在教程代码最前面加一行`paddle.enable_static()`，或者先使用Paddle1.8版本，后续我们会修复这个问题

**Comment by xbzd315** [comment] 2021-06-04 02:13
It doesn't seem to be resolved yet
Duplicate of #

**Closed as completed** 2024-02-06 02:58 UTC
